### ISSUE TITLE
[Next] channel.permission_overwrites

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/Discordeno#156]
A pr targeting the next branch as this is a breaking change should be made to rename this to channel.permissions or channel.overwrites or something not entirely sure what the best name is.

**Comment by ayntee** [comment]
Just `permissions` and `overwrites` would be ambiguous since guild channels do not have their own *permissions*, it "borrows" permissions from roles and the permission can be overwritten for a specific guild channel.
What do you think about renaming it to `permissionOverwrites`? If not `permissionOverwrites`, I would recommend *channel.permissions*.

**Comment by Skillz4Killz** [comment]
Whatever you think best, personally i dont mind i prefer more explicit so permissionOverwrites for me.
