### ISSUE TITLE
Segregate API types from the core

### ISSUE THREAD

**Issue by ayntee** [Skillz4Killz/Discordeno#176]
**Is your feature request related to a problem? Please describe.**

I think it would be better to divide the Discord API types or the types directory into a different repository, specifically created for the API types; essentially to remove clutter from the main codebase. Moreover, the repository will be activity-maintained with types for all API versions.

**Comment by Skillz4Killz** [comment]
I dont like this idea, will elaborate on reasons when im more free just wanted you to know quickly in case u wanted to work on this. This is not something that is good to do.

**Comment by ayntee** [comment]
One of the deductions I forgot to mention is that the current API types are not completely compliant with the latest version of API, namely v8.

**Comment by Skillz4Killz** [comment]
Alrighty so let's break this down.

1. Separate repo for types only makes maintenance worse. 
2. Discord is no longer going to support uses of different API versions so the entire purpose of having multiple goes out the window. With what happened to v7 of the Discord API because of other libraries choosing to push all users to an unstable and undocumented library version Discord is going to stop allowing using newer versions. That means the only 2 versions we can use atm is v6, v7, and v8.
Note in a few months, v6 & v7 are going to be turned off so any work done to build or maintain typings for them goes out the window. So all our types should prioritize v8.
3. When v9 is being released by Discord in the future we will have a deprecation period for which we will create a PR to update to the new version which will update the types accordingly.

---

One of the main goals of this library was not to worry about backward compatibility.

![image](https://user-images.githubusercontent.com/23035000/98567712-40019000-227e-11eb-9fff-5e4539690310.png)


We should not spend any time trying to maintain things that are going to die out. Our goal should be to provide the very best library possible.

Anyone wanting to use an older version like v6 can still use any of our commits or tags/releases that support it. When they are ready to upgrade, they also get the best and latest changes.

---

@ayntee If there are any issues in the typings we should just patch those, please. Moving them to a separate repo would not resolve them.
