### ISSUE TITLE
Get all items from cache handler

### ISSUE THREAD

**Issue by ayntee** [Skillz4Killz/Discordeno#194]
Cache handler should have entries, keys, and values methods; or a `getAll()` method.

Related: #193

**Comment by Skillz4Killz** [comment]
Can you give me an example of how this would be good to add? The cache handler functions that users can add, allow DD to get access to their custom handling. Essentially, its so that internally in the lib we can handle these functions using their handler. But we don't really need entries, keys, values, getall in the lib so would this not just create extra confusion?

**Comment by ayntee** [comment]
> Can you give me an example of how this would be good to add? The cache handler functions that users can add, allow DD to get access to their custom handling. Essentially, its so that internally in the lib we can handle these functions using their handler. But we don't really need entries, keys, values, getall in the lib so would this not just create extra confusion?

a `getAll()` function should return all the key-value pairs from the cache. But since we are following map spec, instead of a getAll() method, we should support entries(), keys(), and values().

**Comment by Skillz4Killz** [comment]
@ayntee But where in DD do we need a getAll or any of the others?

**Comment by ayntee** [comment]
> @ayntee But where in DD do we need a getAll or any of the others?

For instance, a leaderboard can be easily implemented if `getAll()` existed.

**Comment by Skillz4Killz** [comment]
@ayntee No no, what i mean is cacheHandler functions are meant to be for internal lib purposes. We don't do leaderboards. The user would. They would have access to their redis and handle it through their own redis system for example.

On our end we need certain functionality in order to make the lib work and thats where these functions come from
