### ISSUE TITLE
The library errors out with Deno 1.0.1 + 

### ISSUE THREAD

**Issue by EternallLight** [Skillz4Killz/Discordeno#49]
**Describe the bug**
When trying to run a bot with updated Deno, it won't start.

**To Reproduce**
Try to upgrade Deno to the latest version (ATM, 1.0.2) and start the bot.

```
Andreys-MBP$ deno run --allow-read --allow-net --allow-env --unstable mod.ts 
error: Uncaught Error: Uncaught TypeError: Invalid URL.
    at WorkerImpl.#poll ($deno$/web/workers.ts:210:17)
```
A similar thing happens if I run the bot in Docker with Deno 1.0.1.
With 1.0.0, everything works as expected.

**Expected behavior**
The bot is to start and connect to Discord

**Comment by AngelOnFira** [comment]
Don't know if this is helpful, but I'm getting the error from a different location

```
Compile file:///home/forest/Documents/git/discord-game-engine/mod.ts                                                       
error: Uncaught Error: REQUEST_CLIENT_ERROR                                                                                
      throw new Error(Errors.REQUEST_CLIENT_ERROR);
            ^
    at handleStatusCode (https://raw.githubusercontent.com/Skillz4Killz/Discordeno/v2/module/requestManager.ts:183:13)
    at Object.callback (https://raw.githubusercontent.com/Skillz4Killz/Discordeno/v2/module/requestManager.ts:132:9)
    at async processQueue (https://raw.githubusercontent.com/Skillz4Killz/Discordeno/v2/module/requestManager.ts:55:7)
error: Failed at the start script
error: Failed at the dev script
```

**Comment by Skillz4Killz** [comment]
I am actually using Deno 1.0.2 right now it seems to be working fine.

![image](https://user-images.githubusercontent.com/23035000/82738880-060cf380-9d09-11ea-9270-3e9d47969fae.png)


@EternallLight My guess is that somewhere you are adding a using a url that is invalid. Was there something specific that you are doing while bot is starting up that could trigger that? Perhaps something in one of your event handler functions.

@AngelOnFira This is an interesting issue, but i don't think its related to the Deno version. My first recommendation would be to upgrade to v3 as there were a ton of improvements to the library. If you still see issues, I would check the ClientOptions being passed in if everything is accurate. I will add some logs in a commit later today so that it is possible to get detailed logs.

**Comment by EternallLight** [comment]
I have just managed to get the bot online after upgrading to v4 and fixing some type errors afterwards. Thanks for the response!

**Comment by amatiasq** [comment]
If you are here for @AngelOnFira's comment [this issue](https://github.com/Skillz4Killz/Discordeno/issues/57) will be of your interest.
