### ISSUE TITLE
Embed_Footer type is wrong.

### ISSUE THREAD

**Issue by acarsy01** [Skillz4Killz/Discordeno#81]
**Describe the bug**
Embed_Footer has wrong property based Discord API. iconURL must be icon_url.

**Screenshots**
![image](https://user-images.githubusercontent.com/67241967/89066847-d6b4db80-d376-11ea-9b98-2429c277cb8f.png)
![image](https://user-images.githubusercontent.com/67241967/89066864-dddbe980-d376-11ea-8396-37b7f2559dfe.png)

**Comment by Skillz4Killz** [comment]
@acarsy01 Hey can you bump to the v7 branch. I believe this was already fixed there. Let me know if you still having issues. I haven't officially released the v7 stuff yet because I want to get some time to finish the new Permission system discord added couple days ago as it will be part of the v7 stuff.

**Comment by acarsy01** [comment]
thanks
